apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-eks-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "todo-eks.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: todo-eks-service
            port:
              number: 5000
  

